parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"cvZe":[function(require,module,exports) {
function r(r){return o(r)||e(r)||t(r)||n()}function n(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}function t(r,n){if(r){if("string"==typeof r)return u(r,n);var t=Object.prototype.toString.call(r).slice(8,-1);return"Object"===t&&r.constructor&&(t=r.constructor.name),"Map"===t||"Set"===t?Array.from(r):"Arguments"===t||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t)?u(r,n):void 0}}function e(r){if("undefined"!=typeof Symbol&&null!=r[Symbol.iterator]||null!=r["@@iterator"])return Array.from(r)}function o(r){if(Array.isArray(r))return u(r)}function u(r,n){(null==n||n>r.length)&&(n=r.length);for(var t=0,e=new Array(n);t<n;t++)e[t]=r[t];return e}var i=function(){var r=arguments.length>0&&void 0!==arguments[0]?arguments[0]:[],n=arguments.length>1?arguments[1]:void 0;return n?r.reduce(function(r,t){return!r[t[n]]&&(r[t[n]]=[]),r[t[n]].push(t),r},{}):{}},c=function r(n){return n.reduce(function(n,t){return n.concat(Array.isArray(t)?r(t):t)},[])},a=function(){return(arguments.length>0&&void 0!==arguments[0]?arguments[0]:[]).reduce(function(n,t){return n.includes(t)?n:[].concat(r(n),[t])},[])},f=function(r,n){return r.reduce(function(r,t){return t[n]+r},0)};module.exports={keysDiff:function(){var r=arguments.length>0&&void 0!==arguments[0]?arguments[0]:[],n=arguments.length>1?arguments[1]:void 0,t={};return r.reduce(function(r,e){return!t[e[n]]&&(t[e[n]]=r.push(e)),r},[])},difference:function(){var r=arguments.length>0&&void 0!==arguments[0]?arguments[0]:[],n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:[];return r.reduce(function(r,t){return!n.includes(t)&&r.push(t),r},[])},uniq:a,group:i,flatMap:c,objSum:f};
},{}],"cc51":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.debounce=t;var e=null;function t(t){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:500,o=arguments.length>2&&void 0!==arguments[2]&&arguments[2];if(null!==e&&clearTimeout(e),o){var u=!e;e=setTimeout(function(){e=null},n),u&&"function"==typeof t&&t()}else e=setTimeout(function(){"function"==typeof t&&t()},n)}
},{}],"Tgev":[function(require,module,exports) {
"use strict";var t,e;function o(o){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:500;!(arguments.length>2&&void 0!==arguments[2])||arguments[2]?e||(e=!0,"function"==typeof o&&o(),t=setTimeout(function(){e=!1},n)):e||(e=!0,t=setTimeout(function(){e=!1,"function"==typeof o&&o()},n))}Object.defineProperty(exports,"__esModule",{value:!0}),exports.throttle=o;
},{}],"QDJI":[function(require,module,exports) {
"use strict";function e(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"yyyy-mm-dd";e||(e=Number(new Date)),10==e.toString().length&&(e*=1e3);var r,n=new Date(e),a={"y+":n.getFullYear().toString(),"m+":(n.getMonth()+1).toString(),"d+":n.getDate().toString(),"h+":n.getHours().toString(),"M+":n.getMinutes().toString(),"s+":n.getSeconds().toString()};for(var o in a)(r=new RegExp("("+o+")").exec(t))&&(t=t.replace(r[1],1==r[1].length?a[o]:a[o].padStart(r[1].length,"0")));return t}function t(){var t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,r=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"yyyy-mm-dd";t||(t=Number(new Date)),10==t.toString().length&&(t*=1e3);var n=+new Date(Number(t)),a=(Number(new Date)-n)/1e3,o="";switch(!0){case a<300:o="刚刚";break;case a>=300&&a<3600:o=parseInt(a/60)+"分钟前";break;case a>=3600&&a<86400:o=parseInt(a/3600)+"小时前";break;case a>=86400&&a<2592e3:o=parseInt(a/86400)+"天前";break;default:o=!1===r?a>=2592e3&&a<31536e3?parseInt(a/2592e3)+"个月前":parseInt(a/31536e3)+"年前":e(n,r)}return o}Object.defineProperty(exports,"__esModule",{value:!0}),exports.timeFormat=e,exports.timeFrom=t;
},{}],"g3h8":[function(require,module,exports) {
"use strict";function e(e){return/^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/.test(e)}Object.defineProperty(exports,"__esModule",{value:!0}),exports.validEmail=e;
},{}],"aEGV":[function(require,module,exports) {
module.exports={arrUtils:require("./arrUtils.js"),debounce:require("./debounce.js"),throttle:require("./throttle.js"),tiimeFrom:require("./tiimeFrom.js"),validate:require("./validate.js")};
},{"./arrUtils.js":"cvZe","./debounce.js":"cc51","./throttle.js":"Tgev","./tiimeFrom.js":"QDJI","./validate.js":"g3h8"}],"Focm":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=r(require("./function/*.js"));function t(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap,n=new WeakMap;return(t=function(e){return e?n:r})(e)}function r(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var n=t(r);if(n&&n.has(e))return n.get(e);var o={},u=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var f in e)if("default"!==f&&Object.prototype.hasOwnProperty.call(e,f)){var i=u?Object.getOwnPropertyDescriptor(e,f):null;i&&(i.get||i.set)?Object.defineProperty(o,f,i):o[f]=e[f]}return o.default=e,n&&n.set(e,o),o}var n={},o=function(t){Object.keys(e.default).forEach(function(t){Object.assign(n,e.default[t])}),t.prototype.$hks=n},u=o;exports.default=u,"undefined"!=typeof window&&window.Vue&&(window.Vue.use(o),o.installed&&(o.installed=!1));
},{"./function/*.js":"aEGV"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map